// Auto-generated puzzle data from Lichess open puzzle database
// lichess.org/training – CC0 license
// Generated by extract_puzzles.js

const LICHESS_PUZZLES = [
  {
    "id": "000rZ",
    "difficulty": "beginner",
    "theme": "Mate in 1",
    "rating": 523,
    "fen": "2kr1b1r/p1p2pp1/2pqb3/7p/3N2n1/2NPB3/PPP2PPP/R2Q1RK1 w - - 2 13",
    "opponentMove": {
      "from": {
        "row": 4,
        "col": 3
      },
      "to": {
        "row": 2,
        "col": 4
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 2,
        "col": 3
      },
      "to": {
        "row": 6,
        "col": 7
      },
      "promotion": null
    },
    "solutionUCI": "d6h2",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/seIMDWkD#25"
  },
  {
    "id": "001KR",
    "difficulty": "beginner",
    "theme": "Mate in 1",
    "rating": 645,
    "fen": "6Qk/p1p3pp/4N3/1p6/2q1r1n1/2B5/PP4PP/3R1R1K b - - 0 28",
    "opponentMove": {
      "from": {
        "row": 0,
        "col": 7
      },
      "to": {
        "row": 0,
        "col": 6
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 7,
        "col": 5
      },
      "to": {
        "row": 0,
        "col": 5
      },
      "promotion": null
    },
    "solutionUCI": "f1f8",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/TaT1Zl7z/black#56"
  },
  {
    "id": "001pC",
    "difficulty": "beginner",
    "theme": "Mate in 1",
    "rating": 870,
    "fen": "r4rk1/pp3ppp/3b4/2p1pPB1/7N/2PP3n/PP4PP/R2Q1RqK w - - 5 18",
    "opponentMove": {
      "from": {
        "row": 7,
        "col": 5
      },
      "to": {
        "row": 7,
        "col": 6
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 5,
        "col": 7
      },
      "to": {
        "row": 6,
        "col": 5
      },
      "promotion": null
    },
    "solutionUCI": "h3f2",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/d04UP3XD#35"
  },
  {
    "id": "001wb",
    "difficulty": "beginner",
    "theme": "Mate in 1",
    "rating": 1144,
    "fen": "r3k2r/pb1p1ppp/1b4q1/1Q2P3/8/2NP1Pn1/PP4PP/R1B2R1K w kq - 1 17",
    "opponentMove": {
      "from": {
        "row": 6,
        "col": 7
      },
      "to": {
        "row": 5,
        "col": 6
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 2,
        "col": 6
      },
      "to": {
        "row": 3,
        "col": 7
      },
      "promotion": null
    },
    "solutionUCI": "g6h5",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/hNzYRMWP#33"
  },
  {
    "id": "002HE",
    "difficulty": "beginner",
    "theme": "Mate in 1",
    "rating": 1116,
    "fen": "1qr2rk1/1p1p1ppp/pB2p1n1/7n/2P1P3/1Q2NP1P/PP2B1Pb/3R1RK1 w - - 1 20",
    "opponentMove": {
      "from": {
        "row": 7,
        "col": 6
      },
      "to": {
        "row": 6,
        "col": 5
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 0,
        "col": 1
      },
      "to": {
        "row": 5,
        "col": 6
      },
      "promotion": null
    },
    "solutionUCI": "b8g3",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/U21EXYdv#39"
  },
  {
    "id": "002Q2",
    "difficulty": "beginner",
    "theme": "Mate in 1",
    "rating": 925,
    "fen": "7k/p4R1p/3p3r/2pN1n2/2PbBBb1/3P2P1/P3r3/5R1K w - - 1 28",
    "opponentMove": {
      "from": {
        "row": 4,
        "col": 5
      },
      "to": {
        "row": 2,
        "col": 7
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 3,
        "col": 5
      },
      "to": {
        "row": 5,
        "col": 6
      },
      "promotion": null
    },
    "solutionUCI": "f5g3",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/yqAJ1jMv#55"
  },
  {
    "id": "002vV",
    "difficulty": "beginner",
    "theme": "Mate in 1",
    "rating": 492,
    "fen": "8/6k1/2R4p/5p1P/5P1K/6P1/8/r7 w - - 2 58",
    "opponentMove": {
      "from": {
        "row": 2,
        "col": 2
      },
      "to": {
        "row": 2,
        "col": 1
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 7,
        "col": 0
      },
      "to": {
        "row": 7,
        "col": 7
      },
      "promotion": null
    },
    "solutionUCI": "a1h1",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/KB7FAntf#115"
  },
  {
    "id": "003AX",
    "difficulty": "beginner",
    "theme": "Mate in 1",
    "rating": 1070,
    "fen": "2r2rk1/5ppp/bq2p3/p1ppP1N1/Pb1P2P1/1P2P2P/2QN4/2R1K2R b K - 1 18",
    "opponentMove": {
      "from": {
        "row": 3,
        "col": 2
      },
      "to": {
        "row": 4,
        "col": 3
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 6,
        "col": 2
      },
      "to": {
        "row": 1,
        "col": 7
      },
      "promotion": null
    },
    "solutionUCI": "c2h7",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/kRgejRSt/black#36"
  },
  {
    "id": "00465",
    "difficulty": "beginner",
    "theme": "Mate in 1",
    "rating": 578,
    "fen": "3r1Q1k/pp4pp/2p5/6q1/5R2/2P5/P1P2PPP/3rR1K1 b - - 8 27",
    "opponentMove": {
      "from": {
        "row": 0,
        "col": 3
      },
      "to": {
        "row": 0,
        "col": 5
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 4,
        "col": 5
      },
      "to": {
        "row": 0,
        "col": 5
      },
      "promotion": null
    },
    "solutionUCI": "f4f8",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/h21VtqGG/black#54"
  },
  {
    "id": "004WZ",
    "difficulty": "beginner",
    "theme": "Mate in 1",
    "rating": 912,
    "fen": "r6k/1b3pp1/p1q1pn1p/2p5/P1B5/1PN4Q/2P1RP1P/R4Kr1 w - - 2 26",
    "opponentMove": {
      "from": {
        "row": 7,
        "col": 5
      },
      "to": {
        "row": 7,
        "col": 6
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 2,
        "col": 2
      },
      "to": {
        "row": 7,
        "col": 7
      },
      "promotion": null
    },
    "solutionUCI": "c6h1",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/BQIdXPOM#51"
  },
  {
    "id": "004JD",
    "difficulty": "intermediate",
    "theme": "Mate in 1",
    "rating": 1297,
    "fen": "3r4/R7/2p5/p1P2p2/1p4k1/nP6/P2KNP2/8 w - - 3 41",
    "opponentMove": {
      "from": {
        "row": 6,
        "col": 3
      },
      "to": {
        "row": 5,
        "col": 4
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 5,
        "col": 0
      },
      "to": {
        "row": 6,
        "col": 2
      },
      "promotion": null
    },
    "solutionUCI": "a3c2",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/6vTeEc3x#81"
  },
  {
    "id": "004zI",
    "difficulty": "intermediate",
    "theme": "Mate in 1",
    "rating": 1443,
    "fen": "2q3k1/4br1p/6RQ/1p1n2p1/7P/1P4P1/1B2PP2/6K1 b - - 0 27",
    "opponentMove": {
      "from": {
        "row": 1,
        "col": 7
      },
      "to": {
        "row": 2,
        "col": 6
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 2,
        "col": 7
      },
      "to": {
        "row": 0,
        "col": 7
      },
      "promotion": null
    },
    "solutionUCI": "h6h8",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/HE33gdt4/black#54"
  },
  {
    "id": "005wJ",
    "difficulty": "intermediate",
    "theme": "Mate in 1",
    "rating": 1389,
    "fen": "r3kb1r/ppqn1ppp/4pn2/1Q2Nb2/3P4/8/PP2PPPP/RNB1KB1R w KQkq - 4 9",
    "opponentMove": {
      "from": {
        "row": 3,
        "col": 4
      },
      "to": {
        "row": 1,
        "col": 3
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 1,
        "col": 2
      },
      "to": {
        "row": 7,
        "col": 2
      },
      "promotion": null
    },
    "solutionUCI": "c7c1",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/2mU9GJhQ#17"
  },
  {
    "id": "00CWE",
    "difficulty": "intermediate",
    "theme": "Mate in 1",
    "rating": 1386,
    "fen": "3r4/1p4p1/2pBkbBp/p1P5/3rp3/P7/1PK2P2/4R3 b - - 1 31",
    "opponentMove": {
      "from": {
        "row": 2,
        "col": 4
      },
      "to": {
        "row": 3,
        "col": 3
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 2,
        "col": 6
      },
      "to": {
        "row": 1,
        "col": 5
      },
      "promotion": null
    },
    "solutionUCI": "g6f7",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/VCQ4NAd0/black#62"
  },
  {
    "id": "00H1C",
    "difficulty": "intermediate",
    "theme": "Mate in 1",
    "rating": 1242,
    "fen": "r3r3/1kpRnqpp/p4p2/Qp2P2P/1N6/4Pb2/PPP3P1/2K2R2 b - - 0 22",
    "opponentMove": {
      "from": {
        "row": 1,
        "col": 4
      },
      "to": {
        "row": 2,
        "col": 2
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 3,
        "col": 0
      },
      "to": {
        "row": 1,
        "col": 2
      },
      "promotion": null
    },
    "solutionUCI": "a5c7",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/GzcjOw0p/black#44"
  },
  {
    "id": "00HoG",
    "difficulty": "intermediate",
    "theme": "Mate in 1",
    "rating": 1496,
    "fen": "5r1k/5r2/2b2RQp/1p1p2p1/1q4P1/8/8/1B3R1K b - - 0 36",
    "opponentMove": {
      "from": {
        "row": 1,
        "col": 5
      },
      "to": {
        "row": 2,
        "col": 5
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 2,
        "col": 6
      },
      "to": {
        "row": 1,
        "col": 7
      },
      "promotion": null
    },
    "solutionUCI": "g6h7",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/zwJu9mKP/black#72"
  },
  {
    "id": "00Hut",
    "difficulty": "intermediate",
    "theme": "Mate in 1",
    "rating": 1278,
    "fen": "r4rk1/4p1bp/3p2p1/q1pP1P2/4QP2/4B3/1p5P/1BKR3R w - - 0 22",
    "opponentMove": {
      "from": {
        "row": 7,
        "col": 2
      },
      "to": {
        "row": 6,
        "col": 2
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 3,
        "col": 0
      },
      "to": {
        "row": 5,
        "col": 2
      },
      "promotion": null
    },
    "solutionUCI": "a5c3",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/wzUXW4h3#43"
  },
  {
    "id": "00IPp",
    "difficulty": "intermediate",
    "theme": "Mate in 1",
    "rating": 1553,
    "fen": "4Q3/6pk/p3p2p/5p2/1p1P2P1/4q2P/2B1n2B/7K w - - 0 35",
    "opponentMove": {
      "from": {
        "row": 4,
        "col": 6
      },
      "to": {
        "row": 3,
        "col": 5
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 5,
        "col": 4
      },
      "to": {
        "row": 5,
        "col": 5
      },
      "promotion": null
    },
    "solutionUCI": "e3f3",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/JKNcTJw1#69"
  },
  {
    "id": "00Mbv",
    "difficulty": "intermediate",
    "theme": "Mate in 1",
    "rating": 1559,
    "fen": "2k2b1r/pp3ppp/1n6/BN2p1P1/2Q1Nn1P/8/PP3P2/2KR4 b - - 0 24",
    "opponentMove": {
      "from": {
        "row": 2,
        "col": 1
      },
      "to": {
        "row": 4,
        "col": 2
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 7,
        "col": 3
      },
      "to": {
        "row": 0,
        "col": 3
      },
      "promotion": null
    },
    "solutionUCI": "d1d8",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/h1QfViUk/black#48"
  },
  {
    "id": "00O9q",
    "difficulty": "intermediate",
    "theme": "Mate in 1",
    "rating": 1247,
    "fen": "5r2/5p1k/4nP2/4N1p1/8/6P1/6K1/R7 b - - 1 78",
    "opponentMove": {
      "from": {
        "row": 1,
        "col": 7
      },
      "to": {
        "row": 2,
        "col": 7
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 7,
        "col": 0
      },
      "to": {
        "row": 7,
        "col": 7
      },
      "promotion": null
    },
    "solutionUCI": "a1h1",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/0XcQGKAN/black#156"
  },
  {
    "id": "001cr",
    "difficulty": "advanced",
    "theme": "Mate in 1",
    "rating": 1679,
    "fen": "8/3B2pp/p5k1/2p3P1/1p1p1K2/8/1P6/8 b - - 0 38",
    "opponentMove": {
      "from": {
        "row": 3,
        "col": 2
      },
      "to": {
        "row": 4,
        "col": 2
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 1,
        "col": 3
      },
      "to": {
        "row": 0,
        "col": 4
      },
      "promotion": null
    },
    "solutionUCI": "d7e8",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/7FFNwibw/black#76"
  },
  {
    "id": "003IX",
    "difficulty": "advanced",
    "theme": "Mate in 1",
    "rating": 1709,
    "fen": "8/3pk3/R7/1R2Pp1p/2PPnKr1/8/8/8 w - - 4 43",
    "opponentMove": {
      "from": {
        "row": 4,
        "col": 5
      },
      "to": {
        "row": 3,
        "col": 5
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 4,
        "col": 4
      },
      "to": {
        "row": 5,
        "col": 6
      },
      "promotion": null
    },
    "solutionUCI": "e4g3",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/576Btq56#85"
  },
  {
    "id": "00Qqp",
    "difficulty": "advanced",
    "theme": "Mate in 1",
    "rating": 1722,
    "fen": "6k1/8/p3P1p1/8/8/2P3PP/1r5r/R3RK2 w - - 0 46",
    "opponentMove": {
      "from": {
        "row": 2,
        "col": 4
      },
      "to": {
        "row": 1,
        "col": 4
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 6,
        "col": 7
      },
      "to": {
        "row": 7,
        "col": 7
      },
      "promotion": null
    },
    "solutionUCI": "h2h1",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/KZM4JRxc#91"
  },
  {
    "id": "00VIe",
    "difficulty": "advanced",
    "theme": "Mate in 1",
    "rating": 1738,
    "fen": "8/8/8/P6p/8/2RnkN2/r7/3K4 w - - 1 60",
    "opponentMove": {
      "from": {
        "row": 5,
        "col": 5
      },
      "to": {
        "row": 7,
        "col": 4
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 6,
        "col": 0
      },
      "to": {
        "row": 6,
        "col": 3
      },
      "promotion": null
    },
    "solutionUCI": "a2d2",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/ugqyRWZm#119"
  },
  {
    "id": "00j1r",
    "difficulty": "advanced",
    "theme": "Mate in 1",
    "rating": 1628,
    "fen": "8/2rkb3/1p6/6P1/5q2/3R4/Q1P1K3/8 b - - 4 37",
    "opponentMove": {
      "from": {
        "row": 1,
        "col": 3
      },
      "to": {
        "row": 2,
        "col": 2
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 6,
        "col": 0
      },
      "to": {
        "row": 3,
        "col": 3
      },
      "promotion": null
    },
    "solutionUCI": "a2d5",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/2Nj3D5mV/black#74"
  },
  {
    "id": "00y2j",
    "difficulty": "advanced",
    "theme": "Mate in 1",
    "rating": 1663,
    "fen": "3r4/1pB3kp/2b1Pp2/1pN2RpK/1P6/7P/6r1/8 w - - 0 34",
    "opponentMove": {
      "from": {
        "row": 1,
        "col": 2
      },
      "to": {
        "row": 0,
        "col": 3
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 2,
        "col": 2
      },
      "to": {
        "row": 0,
        "col": 4
      },
      "promotion": null
    },
    "solutionUCI": "c6e8",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/5qeC9Wl2#67"
  },
  {
    "id": "00zqB",
    "difficulty": "advanced",
    "theme": "Mate in 1",
    "rating": 1853,
    "fen": "3r1rk1/pp6/5pb1/2p2q2/8/P2P4/1PP4Q/2K3RR b - - 1 27",
    "opponentMove": {
      "from": {
        "row": 3,
        "col": 2
      },
      "to": {
        "row": 4,
        "col": 2
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 6,
        "col": 7
      },
      "to": {
        "row": 1,
        "col": 7
      },
      "promotion": null
    },
    "solutionUCI": "h2h7",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/EURKTOGv/black#54"
  },
  {
    "id": "016fz",
    "difficulty": "advanced",
    "theme": "Mate in 1",
    "rating": 1716,
    "fen": "8/8/3R4/1P3k2/2Bb2pK/8/7r/8 w - - 1 63",
    "opponentMove": {
      "from": {
        "row": 4,
        "col": 7
      },
      "to": {
        "row": 5,
        "col": 6
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 4,
        "col": 3
      },
      "to": {
        "row": 3,
        "col": 4
      },
      "promotion": null
    },
    "solutionUCI": "d4e5",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/jAbGFT6B#125"
  },
  {
    "id": "01HoZ",
    "difficulty": "advanced",
    "theme": "Mate in 1",
    "rating": 1783,
    "fen": "r5rk/1p3p1p/1b1p1p2/pP1P3q/P1P1Pn2/3B1NK1/5P2/R2Q3R w - - 8 28",
    "opponentMove": {
      "from": {
        "row": 5,
        "col": 6
      },
      "to": {
        "row": 4,
        "col": 5
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 3,
        "col": 7
      },
      "to": {
        "row": 4,
        "col": 6
      },
      "promotion": null
    },
    "solutionUCI": "h5g4",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/VOay9YDM#55"
  },
  {
    "id": "01a5v",
    "difficulty": "advanced",
    "theme": "Mate in 1",
    "rating": 1871,
    "fen": "4r2k/R7/1p6/5ppp/3P1P1K/4P3/PP2QPq1/2R5 w - - 0 32",
    "opponentMove": {
      "from": {
        "row": 4,
        "col": 5
      },
      "to": {
        "row": 3,
        "col": 6
      },
      "promotion": null
    },
    "solution": {
      "from": {
        "row": 6,
        "col": 6
      },
      "to": {
        "row": 6,
        "col": 7
      },
      "promotion": null
    },
    "solutionUCI": "g2h2",
    "hint": "There is a checkmate in one move.",
    "lichessUrl": "https://lichess.org/NLOK8h0L#63"
  }
];
